version: "3.4"

services:
  web:
    image: kac0051/redis_nginx_php
    ports:
      - "80:80"
    networks: 
      - web-net
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - db 
      - mongodb
    volumes:
      - redis-data:/redis-data

  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGODB_USER=user 
      - MONGODB_PASS=pass
    volumes:
      - mongo-data:/data/db
    ports:
        - 27017:27017
    networks: 
      - web-net
      
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    networks: 
      - web-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1
    networks: 
      - web-net

networks: 
  web-net:
volumes:
  redis-data:
  mongo-data:
